app:
  name: ModerationService
  version: "1.0"
  debug: true

server:
  host: "0.0.0.0"
  port: 3000

kafka:
  brokers:
    - "localhost:9092"
  topic: "moderation-requests"
  group_id: "moderator-group"

logging:
  level: "debug"
